"""
Some pre-selected urban sites characterized with low station coverage and medium State's buildings coverage.
These sites have been chosen after a naive screening of maps featuring both coverages.
Warning: this first screening is non-exhaustive and does not include all DROM-COM. 
Warning: this first prototype does not manage homonyms
"""

low_coverage_sites = {
    "Ain": ["Gex"],
    "Aisne": ["Laon", "Soissons"],
    "Allier": ["Moulins", "Vichy"],
    "Alpes-de-Haute-Provence": ["Manosque", "Forcalquier"],
    "Alpes-Maritimes": ["Saint-Etienne-de-Tinée", "Menton", "Monaco"],
    "Ardèche": ["Privas"],
    "Ardennes": ["Buzancy"],
    "Ariège": ["Foix"],
    "Aube": ["Romilly-sur-Seine", "Ramerupt"],
    "Aude": ["Castelnaudary"],
    "Aveyron": ["Rodez", "Baraqueville", "Laissac"],
    "Bas-Rhin": [],
    "Bouches-du-Rhône": ["Arles", "Saintes-Maries-de-la-Mer"],
    "Calvados": ["Honfleur", "Trouville", "Deauville"],
    "Cantal": ["Saint-Flour"],
    "Charente": ["Angoulême", "Ruffec"],
    "Charente-Maritime": ["Saintes", "Jonzac"],
    "Cher": ["Aubigny-sur-Nère", "Vierzon"],
    "Corrèze": ["Tulle", "Brive-la-gaillarde"],
    "Corse du sud" : [],
    "Côte-d'Or": ["Montbard", "Beaune"],
    "Côtes-d'Armor": ["Guingamp", "Loudéac"],
    "Creuse": ["Aubusson", "la Souterraine"],
    "Deux-Sèvres": ["Parthenay", "Thouars", "Melle"],
    "Dordogne": ["Bergerac", "Ribérac"],
    "Doubs": [],
    "Drôme": [],
    "Essone": ["Etampes", "Etréchy", "Arpajon"],
    "Eure": ["Evreux", "LesQndelys", "Nonancourt"],
    "Eure-et-Loir": ["Chartres", "Lucé", "Dreux", "Nogent-le-Rotrou"],
    "Finistère": ["Roscoff", "Morlaix", "Carantec", "Loctudy", "Quimper", "Ouessant"],
    "Gard": ["Nîmes"],
    "Gers": ["Auch", "Vic-Fezensac", "L'Isle-Jourdain", "Lectoure"],
    "Gironde": ["Langon"],
    "Haute-Corse" : ["Calvi"],
    "Haute-Garonne": ["Saint-Gaudens", "Bagnères-de-Luchon", "Montréjeau"],
    "Haute-Loire": ["Brioude", "LaChaise-Dieu", "Blesle"],
    "Haute-Marne": ["Saint-Dizier", "Langres", "Prauthoy"],
    "Hautes-Alpes": ["Serres", "Rosans", "Laragne-Montéglin", "Barcillonnette"],
    "Haute-Saône": ["Vesoul", "Luxeuil-les-Bains", "Gray", "Lure"],
    "Haute-Savoie": ["Annecy"],
    "Hautes-Pyrénées": ["Vieille-Aure", "Saint-Lary-Soulan", "Vic-en-Bigorre"],
    "Haute-Vienne": ["Bellac", "Eymoutiers", "LeDorat"],
    "Haut-Rhin": [],
    "Hérault": ["Lodève", "LeCaylar", "Béziers"],
    "Ile-et-Vilaine": ["Saint-Malo", "Redon"],
    "Indre": ["Châteauroux", "Issoudun", "LeBlanc"],
    "indre-et-loire": ["Amboise", "Chinon"],
    "Isère": [],
    "Jura": ["Lons-le-Saunier", "Saint-Claude", "Dôle"],
    "Landes": ["Biscarosse", "Mimizan-Plage", "Gabarret", "Capbreton"],
    "Loire": ["Roanne", "Saint-Etienne"],
    "Loire-Atlantique": ["Châteaubriant", "LeCroisic", "Blain"],
    "Loiret": ["Pithiviers", "Montargis"],
    "Loir-et-Cher": ["Vendôme", "Saint-Aignan"],
    "Lot": ["Cahors", "Figeac"],
    "Lot-et-Garonne": ["Agen", "Marmande"],
    "Lozère": ["Mende", "Florac"],
    "Maine-et-Loire": ["Saumur", "Cholet"],
    "Manche": [],
    "Marne": ["Sainte-Menehould", "Epernay"],
    "Mayenne": [],
    "Meurthe-et-Moselle": ["Longwy"],
    "Meuse": ["Verdun", "Bar-le-Duc"],
    "Morbihan": [],
    "Moselle": ["Forbach", "Molay-Moselle"],
    "Nièvre": ["Brinon-sur-Beuvron"],
    "Nord": ["Cambrai"],
    "Oise": ["Formerie", "Nanteuil-le-Haudouin"],
    "Orne": [],
    "Paris": [],
    "Pas-de-Calais": ["Berck", "leTourquetParisPlage", "Etaples", "Arras"],
    "Puy-de-Dôme": [],
    "Pyrénées-Atlantiques": ["Bayonne", "Pau"],
    "Pyrénées-Orientales": ["Collioure", "Prades"],
    "Rhône": [],
    "Saône-et-Loire": ["Autun", "Montceau-les-Mines"],
    "Sarthe": ["LeMans", "Laflèche", "Mamers", "Château-du-Loir"],
    "Savoie": [],
    "Seine-et-Marne": ["Meaux", "Provins", "Champs-sur-Marne", "Torcy"],
    "Seine-Maritime": ["Dieppe", "Fécamp"],
    "Seine-Saint-Denis": ["Saint-Denis", "Aulnay-Sous-Bois"],
    "Somme": [],
    "Tarn": ["Albi", "Gaillac"],
    "Tarn-et-Garonne": [],
    "Val-de-Marne": ["Créteil"],
    "Val d'Oise": [],
    "Var": ["Draguignan"],
    "Vaucluse": ["Carpentras"],
    "Vendée": ["Noirmoutier-en-l'île", "Fromentine", "Les Sables d'Olonne"],
    "Vienne": ["Montmorillon"],
    "Vosges": ["Neufchâteau"],
    "Yonne": ["Auxerre", "Avallon"],
    "Yvelines": [],
    "La Réunion": ["Saint-Pierre", "Saint-Denis"],
    "Martinique" : ["Sainte-Luce"],
    "Guadeloupe": [],
}
